# Project Euler -> Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=begin
# my solution
a = 1
b = 2
sum = 0

while b < 4000000
  x = b
  b = a + b
  a = x

  sum += a if a % 2 == 0
end

puts sum
=end

# Solution found online
sum, x, y = 0, 1, 2
while y < 4000000
  sum += y if y.even?
  x, y = y, x + y
end
puts sum
