# How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2<= b <= 100?

a = b = (2..100).to_a
combinations = a.product(b).map { |x, y| x**y }.uniq
puts combinations.length
